/*
 * File: app/store/LineItems.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Orders.store.LineItems', {
    extend: 'Ext.data.Store',

    requires: [
        'Orders.model.LineItem',
        'Ext.data.proxy.Direct',
        'Orders.DirectAPI'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: false,
            model: 'Orders.model.LineItem',
            storeId: 'LineItems',
            data: [
                {
                    id: 1001,
                    quantityOrdered: 100,
                    perUnitPrice: 500,
                    itemId: 1,
                    totalPrice: 50000,
                    itemName: 'First Item'
                },
                {
                    id: 1002,
                    quantityOrdered: 100,
                    perUnitPrice: 299,
                    itemId: 2,
                    totalPrice: 29900,
                    itemName: 'Second Item'
                }
            ],
            proxy: {
                type: 'direct',
                directFn: 'Fulfill.ss.DXCustomers.getLineItems',
                paramOrder: 'orderId'
            }
        }, cfg)]);
    }
});