/*
 * File: app/store/Orders.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Orders.store.Orders', {
    extend: 'Ext.data.Store',

    requires: [
        'Orders.model.Order',
        'Ext.data.proxy.Direct',
        'Orders.DirectAPI',
        'Ext.util.Sorter'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: false,
            model: 'Orders.model.Order',
            storeId: 'Orders',
            data: [
                {
                    orderNo: 'ADR1123123',
                    id: 200,
                    orderDate: '2013-01-12T00:00:00.000Z',
                    shippedDate: '2013-01-12T00:00:00.000Z',
                    total: 975.25,
                    balance: 123,
                    subTotal: 79900,
                    shipping: 25.25,
                    tax: 50,
                    customer: null
                },
                {
                    orderNo: 'XDR1876889',
                    id: 204,
                    orderDate: '2012-11-10T00:00:00.000Z',
                    shippedDate: '2012-11-10T00:00:00.000Z',
                    total: 234.56,
                    balance: 123,
                    subTotal: 0,
                    shipping: 0,
                    tax: 0,
                    customer: null
                },
                {
                    orderNo: 'EDR0008719',
                    id: 202,
                    orderDate: '2012-07-22T00:00:00.000Z',
                    shippedDate: '2012-07-22T00:00:00.000Z',
                    total: 1234.56,
                    balance: 234,
                    subTotal: 0,
                    shipping: 15,
                    tax: 0,
                    customer: null
                },
                {
                    orderNo: 'SSP8000318',
                    id: 203,
                    orderDate: '2012-03-01T00:00:00.000Z',
                    shippedDate: '2012-03-01T00:00:00.000Z',
                    total: 345.67,
                    balance: 234,
                    subTotal: 0,
                    shipping: 0,
                    tax: 22,
                    customer: null
                },
                {
                    orderNo: 'ATR1008342',
                    id: 201,
                    orderDate: '2012-01-12T00:00:00.000Z',
                    shippedDate: '2012-01-12T00:00:00.000Z',
                    total: 456.78,
                    balance: 345,
                    subTotal: 0,
                    shipping: 20,
                    tax: 50,
                    customer: null
                }
            ],
            proxy: {
                type: 'direct',
                directFn: 'Fulfill.ss.DXCustomers.getOrders',
                paramOrder: 'customerId'
            },
            sorters: {
                direction: 'DESC',
                property: 'orderDate'
            }
        }, cfg)]);
    }
});