/*
 * File: app/store/PeriodTotals.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Orders.store.PeriodTotals', {
    extend: 'Ext.data.Store',

    requires: [
        'Orders.model.PeriodTotal',
        'Ext.data.proxy.Direct',
        'Orders.DirectAPI',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: false,
            model: 'Orders.model.PeriodTotal',
            storeId: 'PeriodTotals',
            data: [
                {
                    quarter: '2012-Q1',
                    total: 138
                },
                {
                    quarter: '2012-Q2',
                    total: 9280
                },
                {
                    quarter: '2012-Q3',
                    total: 12902
                },
                {
                    quarter: '2012-Q4',
                    total: 12448
                },
                {
                    quarter: '2013-Q1',
                    total: 18790
                }
            ],
            proxy: {
                type: 'direct',
                directFn: 'Fulfill.ss.DXCustomers.getCustomerDetail',
                paramOrder: 'customerId',
                reader: {
                    type: 'json',
                    root: 'perPeriodTotals'
                }
            }
        }, cfg)]);
    }
});